force-app/main/default/objects/Custom__c/Custom__c.object-meta.xml
<CustomObject>
    <label>CustomOpportunity</label>
    <nameField>
        <label>Custom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomOpportunies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomOpportunies</relationshipLabel>
    <relationshipName>CustomOpportunies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CustomOpportunies</relationshipLabel>
    <relationshipName>CustomOpportunies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SOQLQuery.cls
public class SOQLQuery
{

    public void query()
    {
        
       List<Student__c> li = new List<Student__C>();
       li= [select name,id from Student__c];
       system.debug(li);
        
        /***** for each loop ********/
        
        for(Student__c sc:li){
            
            sc.name= 'Mr.'+sc.name;
            system.debug(sc.name);
        }
        
        List<Contact> con=  new  List<contact>();
        string val= 'shubham';
        //con= [select name, phone from contact where Account=:val];
        con= [select name, phone from contact where name=:val];
        system.debug(con);
        
        List<Custom__c> c=[SELECT id,Name,Amount__c,Description__c , Account__r.name,Account__r.phone from Custom__c where id='a085g000004Goa0AAC'];
        // to get 18 digit id
        List<Custom__c> d=[SELECT id,Name,Amount__c,Description__c,Account__r.name,Contact__r.LastName,Order_Number__c ,Tracking_Number__c from Custom__c where name='Shubham'];
        system.debug(d); //a085g000004GoaAAAS
        List<Custom__c> e=[SELECT id,Name,Amount__c,Description__c,Account__r.name,Contact__r.LastName,contact__r.phone,Order_Number__c ,Tracking_Number__c from Custom__c where id='a085g000004GoaAAAS'];
        for( Custom__c cs:e){
            system.debug(cs);
             }
        
        List<Custom__c> df= [select Account__r.name , contact__r.title from Custom__c where id='a085g000004GoaAAAS'];
        system.debug(df);
        
        list<case> ef= [select Account.name , contact.title from case where casenumber='00001385'];
        
            system.debug(ef);
             
 
    }
}